#!/bin/bash
cd $(dirname $0)
./helpers/write-http-headers.sh
./helpers/begin-document.sh Call
window=$(echo $QUERY_STRING | cut -d"=" -f2)
echo "
<h1>$(./bash_queue/call.sh $window)</h1>
<a href='/complete?window=$window'>Завершить</a>
"
./helpers/end-document.sh