#!/bin/bash
cd $(dirname $0)
./helpers/write-http-headers.sh
touch ./bash_queue/ready.txt
echo "
<table>
    <thead>
        <tr><th>Билет</th><th>Окно</th></tr>
    </thead>
    <tbody>
"
while read line; do
    window=$(echo $line | cut -d" " -f1)
    ticket=$(echo $line | cut -d" " -f2)
    echo "
        <tr>
            <td>$ticket</td>
            <td>$window</td>
        </tr>
    "
done < ./bash_queue/ready.txt
echo "
    </tbody>
</table>
"
./helpers/inject-tts-script.sh